= osm-street-extractor

IMPORTANT: This tool is will be only maintained. No new features will be added. Please check out the advanced version at https://github.com/dennstack/addrgo

== Description

The osm-street-extractor is a small tool that allows you to convert OpenStreetMap (OSM) files of any German state into CSV format. Feel free to use and modify it as needed.

== Installation

Ensure you have Go installed on your system. For installation instructions, refer to the official Go documentation: https://golang.org/doc/install

Clone the osm-street-extractor repository:

[source,shell]
$ git clone https://github.com/dennstack/osm-street-extractor.git

Change to the project directory:

[source,shell]
$ cd osm-street-extractor

Build the executable:

[source,shell]
$ go build .

Run the tool:

[source,shell]
$ ./osm-street-extractor


== Usage

To convert OSM files into CSV, follow these steps:

Run the tool:

[source,shell]
$ ./osm-street-extractor

The tool will convert the OSM files into CSV format and save the results in the output directory.

== Contributing

Contributions are welcome! If you find any issues or have suggestions for improvements, please open an issue on the project's GitHub repository: https://github.com/dennstack/osm-street-extractor/issues

If you'd like to contribute code, follow these steps:

Fork the repository.

This project is licensed under the MIT License.
